# Generated by Django 4.2.1 on 2023-05-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member_email_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
