# Generated by Django 4.2.1 on 2023-05-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0002_dropdown_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='dropdown',
            field=models.CharField(blank=True, choices=[('Text', 'Text'), ('Image', 'Image')], max_length=200, null=True),
        ),
    ]
