# Generated by Django 4.2.1 on 2023-05-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0003_alter_dropdown_dropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdown',
            name='name',
        ),
        migrations.AddField(
            model_name='dropdown',
            name='audio',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='dropdown',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='dropdown',
            field=models.CharField(blank=True, choices=[('Text', 'Text'), ('Image', 'Image'), ('Audio', 'Audio')], max_length=200, null=True),
        ),
    ]
