# Generated by Django 4.2.1 on 2023-05-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0005_alter_dropdown_audio_alter_dropdown_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='textarea',
            field=models.CharField(max_length=20, verbose_name='Text'),
        ),
    ]
